---
title: "Shiny Exams Report"
output: pdf_document
params:
  df: NULL
  wishlist: NULL
---
```{r Initialization, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(patchwork)
library(knitr)
#Testing code to see whether this thing actually works. 
# df <- read.csv("2024_SS_EUSP.csv")
# df[,c(14,12,3)] <- df[,c(14,12,3)] |> lapply(as.factor)
# wishlist <- data.frame(
#   "Variable"=c("Note.vor.Bonus", "Aufgabe.1", "Aufgabe.2", "Aufgabe.3", "Aufgabe.5", "Gesamt", "Note.nach.Bonus"),
#   "Plot.Type"=c(NA,NA,NA,"Boxplot", "Density Plot", "Histogram", "Boxplot"),
#   "Separator.Variable"=c(NA,NA,NA,"none", "TI", "Bonuspunkte", "TI"),
#   "Exported.Statistics"=c("Min,Max", "Mean,SD,Min,Max","N",NA,NA,NA,NA)
# )
df <- params$df  #extract data frame from list.
df <- as.data.frame(df)
wishlist <- params$wishlist
wishlist <- as.data.frame(wishlist)


#ensure that DF names are syntactically equivalent.
colnames(df) <- make.names(colnames(df))
colnames(wishlist) <- make.names(colnames(wishlist))

#replace none with NA, this should be changed in the main app code at some point.
wishlist[wishlist=="none"] <- NA

#define the plotter function
plotter <- function(dat=NULL,axis1=NULL,filler=NULL,type=NULL){
    p <- dat |> ggplot(aes(x= .data[[{{axis1}}]]))+
      theme(panel.grid.major = element_blank(), 
            panel.background = element_blank(), 
            panel.grid.minor = element_blank(),
            axis.line = element_line(colour = "black"),)
    #add geoms
    if ({{type}} == "Boxplot") {
      p <- p + geom_boxplot() +
        theme(axis.ticks.y = element_blank(), 
              axis.text.y = element_blank())
    } else if ({{type}} == "Density Plot") {
      p <- p + geom_density()
    } else if ({{type}} == "Histogram") {
      p <- p + geom_histogram()
    }
    #add fills
    if (!is.null({{filler}})) {
      if({{type}} == "Boxplot"){
      p <- p + aes(fill = .data[[{{filler}}]]) +
        scale_fill_manual(values = c("#59B4AB", "#D7B365"))
    }else{
      p <- p + facet_wrap(as.formula(paste("~",{{filler}})))
    }
      }
    #add titles
    title <- ifelse(!is.null(filler),paste0({{type}}," of ", {{axis1}}," by ",{{filler}}),paste0({{type}}," of ", {{axis1}}))
    p <- p + labs(title = title)
    return(p)
}
layouter <- function(rows=NULL){
  #determines plot output grid columns based on integer division of row numbers
  x <- c(rows%/%2, rows%/%3)
  y <- which(x==min(x))
  return(ifelse(y==1,2,3))
}
```
## List of Exports
The following items were selected for export.
```{r Exportlist, echo=FALSE, warning=FALSE, message=FALSE}
wl <- wishlist
wl[is.na(wl)] <- ""
kable(wl)
rm(wl)
```

## Detailed Exports
In this section, the detailed reports you chose will be shown.

### Statistics Export
```{r Statistics Export Block, echo=FALSE, warning=FALSE, message=FALSE}
#This whole block is conditional on the wishlist table.
if(sum(is.na(wishlist$Exported.Statistics))!=nrow(wishlist)){
  #Initialize the results table and variables to process
  results <- data.frame()
  vars <- wishlist[!is.na(wishlist$Exported.Statistics), "Variable"]
  #construct a results vector per variable 
  for(i in 1:length(vars)){
    splitter <- str_split_1(wishlist[!is.na(wishlist$Exported.Statistics),"Exported.Statistics"][i], ",")
    #construct the vector. No need to iterate over elements of splitter, as we re-construct the data frame later anyways.
    insert <- c(
        if("Mean" %in% splitter){
          df[vars[i]] |> lapply(function(x){round(mean(x, na.rm = T), digits = 2)})
          }else{NA},
        if("SD" %in% splitter){
          df[vars[i]] |> lapply(function(x){round(sd(x, na.rm = T), digits = 2)})
          }else{NA},
        if("Min" %in% splitter){
          df[vars[i]]|> sapply(min,na.rm = TRUE) 
          }else{NA},
        if("Max" %in% splitter){
          df[vars[i]] |> sapply(max,na.rm = TRUE) 
          }else{NA},
        if("N" %in% splitter){
          df[vars[i]] |> nrow()
          }else{NA})
    names(insert) <- NULL
    results <- rbind(results, insert) #bind results to the df as rows.
  }
  results <- results |> add_column(vars, .before=1)
  #output colnames
  colnames(results) <- c("Variable", "Mean", "Standard Deviation", "Min", "Max", "N")
  #filter out columns that only contain NAs for visual delight.
  #results <- results |> select_if(function(x) !all(is.na(x)))
  results[is.na(results)] <- "not.selected"
  #output the table
  knitr::kable(results)
}
```
### Plot Exports
```{r Plot Output Block, echo=FALSE, warning=FALSE, message=FALSE}
#This section is conditional on Plots being in the section.
if(sum(is.na(wishlist$Plot.Type))!=nrow(wishlist)){
  plots <- list()
  #construct a df
  vars <- wishlist[!is.na(wishlist$Plot.Type),1:3]
  #set NAs to zero so that
  for(i in 1:nrow(vars)){
    x <- vars[i,"Variable"]
    t <- vars[i,"Plot.Type"]
    f <- vars[i,"Separator.Variable"]
    if(is.na(f)){
      p <- plotter(dat=df, axis1 = x, type = t)
    }else{
      p <- plotter(dat = df,axis1 = x, filler = f, type = t)
    }
    plots[[i]] <- p
  }
  wrap_plots(plots,widths = 4, heights = 2 )
  #result <- wrap_plots(plots,ncol = layouter(nrow(vars)))
  #result
}else{
  "No Objects were selected to export."
}
  
```

### About Shiny Exams
ShinyExams was created by Oliver D. Reithmaier. For feature requests, bug reports or other issues, visit [the Project Github Page](https://github.com/K4tana/ShinyExams). 
